server:
  port: ${app.port:8080}
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/test?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

mybatis-plus:
  configuration:
    default-enum-type-handler: com.example.common.BaseEnumTypeHandler
    cache-enabled: false
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/**/*.xml
  global-config:
    db-config:
      logic-delete-field: deleted_at
      logic-not-delete-value: 0
      logic-delete-value: UNIX_TIMESTAMP()